# Generated by Django 3.2 on 2021-05-20 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependents',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dvisit', to='visitinfo.visits'),
        ),
    ]
