# Generated by Django 3.2 on 2021-05-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitinfo', '0003_alter_dependents_visit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependents',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='dependents',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='dependents',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='locations',
            old_name='locationName',
            new_name='location_name',
        ),
        migrations.RenameField(
            model_name='visits',
            old_name='timeOfVisit',
            new_name='time_of_visit',
        ),
    ]
