# Generated by Django 3.2 on 2021-05-23 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitinfo', '0004_auto_20210520_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='houseNumber',
            new_name='house_number',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='PostCode',
            new_name='postcode',
        ),
    ]
