# Generated by Django 3.2 on 2021-05-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='user_type',
            field=models.CharField(choices=[('GENERAL_USER', 'General User'), ('BUSINESS_USER', 'Business User'), ('HEALTH_USER', 'Health User'), ('ORGANISTAION_USER', 'Organistaion User')], default='ORGANISTAION_USER', max_length=17),
        ),
    ]
