# Generated by Django 3.2 on 2021-05-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='test_case',
            field=models.BooleanField(default=False),
        ),
    ]
