# Generated by Django 3.2 on 2021-05-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='user_type',
            field=models.CharField(choices=[('GENERAL_USER', 'General User'), ('BUSINESS_USER', 'Business User'), ('HEALTH_USER', 'Health User'), ('ORGANISATION_USER', 'Organisation User')], default='GENERAL_USER', max_length=17),
        ),
    ]
