# Generated by Django 3.2 on 2021-05-23 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recievedvaccinedose',
            old_name='dosesRecieved',
            new_name='doses_recieved',
        ),
        migrations.RenameField(
            model_name='recievedvaccinedose',
            old_name='lastDoseRecievedData',
            new_name='last_dose_recieved_date',
        ),
        migrations.RenameField(
            model_name='recievedvaccinedose',
            old_name='userID',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='recievedvaccinedose',
            old_name='vaccineID',
            new_name='vaccine',
        ),
    ]
