# Generated by Django 3.2 on 2021-05-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineinfo', '0002_auto_20210523_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccines',
            old_name='dosesRequired',
            new_name='doses_required',
        ),
        migrations.AddField(
            model_name='vaccines',
            name='summary',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
