# Generated by Django 3.2 on 2021-05-24 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vaccineinfo', '0003_auto_20210524_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recievedvaccinedose',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
