# Generated by Django 3.2 on 2021-05-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccineinfo', '0004_alter_recievedvaccinedose_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccines',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
